<?php

namespace AppBundle\Repository;

/**
 * ProfileSimpleUser
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileSimpleUser extends \Doctrine\ORM\EntityRepository
{
}
