mamaison_annonce_gallery:
    resource: "@MamaisonAnnonceBundle/Controller/GalleryController.php"
    type:     annotation

mamaison_annonce_annonce:
    resource: "@MamaisonAnnonceBundle/Controller/AnnonceController.php"
    type:     annotation

mamaison_annonce:
    resource: "@MamaisonAnnonceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
