mamaison_annonce:
    resource: "@MamaisonAnnonceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

mamaison:
    resource: '@MamaisonAnnonceBundle/Controller/'
    type: annotation