mamaison_annonce_gallery:
    resource: "@MamaisonAnnonceBundle/Controller/GalleryController.php"
    type:     annotation

mamaison_annonce_annonce:
    resource: "@MamaisonAnnonceBundle/Controller/AnnonceController.php"
    type:     annotation

mamaison_annonce_annonce:
    resource: "@MamaisonAnnonceBundle/Controller/AnnonceController.php"
    type:     annotation

app_profile:
    resource: "@AppBundle/Controller/ProfileController.php"
    type:     annotation

mamaison_annonce:
    resource: "@MamaisonAnnonceBundle/Resources/config/routing.yml"
    prefix:   /

#fos_user_registration:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
