<?php

namespace Mamaison\AnnonceBundle\Repository;

/**
 * CaracteristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
