services:
  mamaison_annonce.twig.search_extension:
    class: Mamaison\AnnonceBundle\Service\Extensions\SearchExtension
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: twig.extension }